name: ARP Test Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4
      
       # Set all script permissions
      - name: Make test script executable
        run: chmod +x ./tests/*

      # Run Test_Build_Kernel_Module
      - name: Run Test_Build_Kernel_Module
        run: ./tests/Test_Build_Kernel_Module.sh