name: ARP Test Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4
      
      # Install required Kernel Module build dependencies
      - name: Install Build Essentials
        run: sudo apt-get update && sudo apt-get install -y build-essential
      
      # Compile the code
      - name: Compile Code
        run: make

      # Install required Bridge and IP Tools 
      - name: Install Networking Essentials
        run: sudo apt install -y bridge-utils && sudo apt install -y iproute2

      # Create Bridges, Virtual Interfaces, and Namespaces
      - name: Create Bridges, Virtual Interfaces, and Namespaces
        run: |
          sudo ip link add name br1 type bridge
          sudo ip link add veth0 type veth peer name veth1
          sudo ifconfig veth0 hw ether e2:c8:14:a6:4f:ed
          sudo ip link add veth2 type veth peer name veth3
          sudo ifconfig veth3 hw ether  3a:18:70:ca:91:b2
          sudo ip netns add ns1
          sudo ip netns add ns2

      # Set Interfaces in Namespaces
      - name: Assign Interfaces to Namespaces
        run: |
          sudo ip link set veth0 netns ns1
          sudo ip link set veth3 netns ns2

      # Add interfaces to bridges
      - name: Attach Interfaces to Bridge
        run: |
          sudo ip link set veth1 master br1
          sudo ip link set veth2 master br1

      # Set IP addresses for Network Namespaces
      - name: Set Up Namespace Test Enviornment
        run: |
          sudo ip netns exec ns1 ip addr add 192.168.1.1/24 dev veth0
          sudo ip netns exec ns2 ip addr add 192.168.1.2/24 dev veth3
      
      # Bring up All interfaces
      - name: Bring Up Interfaces
        run: |
          sudo ip link set br1 up
          sudo ip link set veth1 up
          sudo ip link set veth2 up
          sudo ip netns exec ns1 ip link set veth0 up
          sudo ip netns exec ns2 ip link set veth3 up
          sudo ip netns exec ns1 ip link set lo up
          sudo ip netns exec ns2 ip link set lo up

      # Install Test Files Dependencies
      - name: Install Python Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          sudo pip3 install scapy
          sudo apt-get install dsniff 

      # Ensure working Testing Environment 
      - name: Basic ARP Request Messages To Ensure Testing Environemnt is Setup 
        run: | 
          sudo ip netns exec ns1 python3 ./tests/ARP_Request_And_Response.py
          sudo dmesg -C


      # Test Case 1
      # Insert the Kernel Module
      - name: Insert Kernel Module
        run: make install

      - name: Test Filtering from Unvalidated Source
       # Expects ARP requests are Dropped by KDAI when no devices have been validated 
       # via DHCP or Static ACL configurations. This means the regular request and response should fail
        run: |
          # Run the ARP request test and capture the output 
          sudo ip netns exec ns1 python3 ./tests/ARP_Request_And_Response.py
          
          # Check dmesg logs for the ARP drop status
          ARP_DROP_STATUS=$(sudo dmesg | grep "ARP RETURN status was: NF_DROP")
          
          # Print the dmesg log for debugging purposes
          sudo echo "dmesg logs:"
          sudo dmesg | tail -n 20  # Print the last 20 lines of dmesg
          
          # If ARP was dropped correctly, the test passed
          if [ -n "$ARP_DROP_STATUS" ]; then
            sudo echo "Test Passed!"
          else
            sudo echo "The ARP Request was Accepted when it should not have been"
            sudo echo "Test Failed!"
            exit 1
          fi

      # Remove Module
      - name: Clean Up Test
        run: |
          sudo dmesg -C
          make remove

          
      # Test Case 2
      # Insert the Kernel Module
      - name: Insert Kernel Module
        run: make install

      - name: Test Malformed ARP Request and Response
       # Expects Malformed Arp Requests Are Dropped by Kdai
        run: |
          # Run the ARP Malformed Request test
          sudo ip netns exec ns1 python3 ./tests/Test_Malformed_ARP.py
          
          # Check dmesg logs for the ARP drop status
          ARP_DROP_STATUS=$(sudo dmesg | grep "ARP RETURN status was: NF_DROP")
          
          # Print the dmesg log for debugging purposes
          sudo echo "dmesg logs:"
          sudo dmesg | tail -n 20  # Print the last 20 lines of dmesg
          
          # If ARP was dropped correctly, the test passed
          if [ -n "$ARP_DROP_STATUS" ]; then
            sudo echo "Test Passed!"
          else
            sudo echo "The ARP Request was met with a response when it should not have been"
            sudo echo "Test Failed!"
            exit 1
          fi

        # Remove Module
      - name: Clean Up Test
        run: |
          sudo dmesg -C
          make remove

      
      # Test Case 3
      # Insert the Kernel Module
      - name: Insert Kernel Module
        run: make install

      - name: Test An Static Entry Exists in the ARP table for the ARP request
       # Expects Packet to be accepted even without DHCP snooping
        run: |
          #Assign static MAC addresses to veth0 and veth3
          sudo ip netns exec ns1 ip link set veth0 down
          sudo ip netns exec ns1 sudo ifconfig veth0 hw ether e2:c8:14:a6:4f:ed
          sudo ip netns exec ns1 ip link set veth0 up

          sudo ip netns exec ns2 ip link set veth3 down
          sudo ip netns exec ns2 sudo ifconfig veth3 hw ether  3a:18:70:ca:91:b2
          sudo ip netns exec ns2 ip link set veth3 up

          #Add Static MAC addresses to veth1 and veth2 on the Switch
          sudo arp -s 192.168.1.1 e2:c8:14:a6:4f:ed -i veth1
          sudo arp -s 192.168.1.2 3a:18:70:ca:91:b2 -i veth2

          # Run the ARP Request and Response script
          sudo ip netns exec ns1 python3 ./tests/ARP_Request_And_Response.py
          
          # Check dmesg logs for the ARP drop status
          ARP_DROP_STATUS=$(sudo dmesg | grep "ARP RETURN status was: NF_ACCEPT")
          
          # Print the dmesg log for debugging purposes
          sudo echo "dmesg logs:"
          sudo dmesg | tail -n 20  # Print the last 20 lines of dmesg
          
          # If ARP ACCEPET was found, then Test passed
          if [ -n "$ARP_DROP_STATUS" ]; then
            sudo echo "Test Passed!"
          else
            sudo echo "The ARP Request was not met with a response"
            sudo echo "Test Failed!"
            exit 1
          fi

        # Remove Module
      - name: Clean Up Test
        run: |
          sudo ip neigh del 192.168.1.1 dev veth1
          sudo ip neigh del 192.168.1.2 dev veth2
          sudo ip neigh flush all
          sudo dmesg -C
          make remove

      # Test Case 4
      # Insert the Kernel Module
      - name: Insert Kernel Module
        run: make install

      - name: Test DAI Allows communicaiton from Acknowledged Sources
       # Expects Packet to be accepted when the server sees a DHCP ACK
        run: |
          # Create and send the switch a Cusotm DHCP packet ACK for both 192.168.1.1 and 192.168.1.2
          sudo ip netns exec ns1 python3 ./tests/DHCP_Snooping.py

          #Send and ARP Request and wait for a Response
          sudo ip netns exec ns1 python3 ./tests/ARP_Request_And_Response.py

          # Check dmesg logs for the ARP drop status
          ARP_DROP_STATUS=$(sudo dmesg | grep "ARP RETURN status was: NF_ACCEPT")
          
          # Print the dmesg log for debugging purposes
          sudo echo "dmesg logs:"
          sudo dmesg | tail -n 20  # Print the last 20 lines of dmesg
          
          # If ARP was found, then the test passed
          if [ -n "$ARP_DROP_STATUS" ]; then
            sudo echo "Test Passed!"
          else
            sudo echo "The ARP Request was met with a response when it should not have been"
            sudo echo "Test Failed!"
            exit 1
          fi

        # Remove Module
      - name: Clean Up Test
        run: |
          sudo dmesg -C
          make remove

      # Test Case 5
      # Insert the Kernel Module
      - name: Insert Kernel Module
        run: make install

      - name: Test DAI Prevents ARP Poisoning
       # Expects Packet to be dropped if conflicting with DHCP snooping
        run: |

          # Create and send the switch a Cusotm DHCP packet ACK for both 192.168.1.1 and 192.168.1.2
          sudo ip netns exec ns1 python3 ./tests/DHCP_Snooping.py

          # Run the ARP Request and Response script
          sudo ip netns exec ns1 sudo arpspoof -i veth0 -t 192.168.1.11 192.168.1.101 &

          # Save the process ID
          ARPSPOOF_PID=$!
 
          # Kill the process after waiting 3 seconds
          sleep 3
          sudo kill $ARPSPOOF_PID
          
          
          # Check dmesg logs for the ARP drop status
          ARP_DROP_STATUS=$(sudo dmesg | grep "ARP RETURN status was: NF_DROP")
          
          # Print the dmesg log for debugging purposes
          sudo echo "dmesg logs:"
          sudo dmesg | tail -n 20  # Print the last 20 lines of dmesg
          
          # If ARP DROP was found, then DAI did not forward the malicious packet.
          if [ -n "$ARP_DROP_STATUS" ]; then
            sudo echo "Test Passed!"
          else
            sudo echo "The ARP Request was met with a response"
            sudo echo "Test Failed!"
            exit 1
          fi

        # Remove Module
      - name: Clean Up Test
        run: |
          sudo dmesg -C
          make remove
