name: ARP Test Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4
      
       # Set all script permissions
      - name: Make test script executable
        run: |
            chmod +x ./tests/testenv/*.sh
            chmod +x ./tests/InitializationOfTheModule/*.sh
            chmod +x ./tests/SettingDynamicParameters/*.sh
            chmod +x ./tests/UsingDynamicParameters/*.sh
            chmod +x ./tests/CoreDAIFeatures/*.sh
            chmod +x ./tests/EdgeCases/*.sh

      # Run Initialization_Of_The_Module Tests
      - name: Run Test_Build_Kernel_Module
        working-directory: ./tests/InitializationOfTheModule/
        run: ./Test_Build_Kernel_Module.sh

      - name: Run Test_Insert_Kernel_Module
        working-directory: ./tests/InitializationOfTheModule/
        run: ./Test_Insert_Kernel_Module.sh

      # Run Setting_Dynamic_Parameters Tests
      - name: Run Test_add_Trusted_Interface
        working-directory: ./tests/SettingDynamicParameters/
        run: ./Test_add_Trusted_Interface.sh

      - name: Run Test_add_Trusted_Interfaces_Malformed
        working-directory: ./tests/SettingDynamicParameters/
        run: ./Test_add_Trusted_Interfaces_Malformed.sh

      - name: Run Test_add_Trusted_Interfaces
        working-directory: ./tests/SettingDynamicParameters/
        run: ./Test_add_Trusted_Interfaces.sh

      - name: Run Test_add_VLAN
        working-directory: ./tests/SettingDynamicParameters/
        run: ./Test_add_VLAN.sh

      - name: Run Test_add_VLANs_Malformed
        working-directory: ./tests/SettingDynamicParameters/
        run: ./Test_add_VLANs_Malformed.sh

      - name: Run Test_add_VLANs
        working-directory: ./tests/SettingDynamicParameters/
        run: ./Test_add_VLANs.sh

      - name: Run Test_set_globally_enabled_DAI
        working-directory: ./tests/SettingDynamicParameters/
        run: ./Test_set_globally_enabled_DAI.sh

      - name: Run Test_set_globally_enabled_DAI_Malformed
        working-directory: ./tests/SettingDynamicParameters/
        run: ./Test_set_globally_enabled_DAI_Malformed.sh

      - name: Run Test_set_static_ACL_Enabled
        working-directory: ./tests/SettingDynamicParameters/
        run: ./Test_set_static_ACL_Enabled.sh

      - name: Run Test_set_static_ACL_Enabled_Malformed
        working-directory: ./tests/SettingDynamicParameters/
        run: ./Test_set_static_ACL_Enabled_Malformed.sh

      # Run Using_Dynamic_Parameters Tests
      - name: Run Test_DAI_VLAN_Filtering
        working-directory: ./tests/UsingDynamicParameters/
        run: ./Test_DAI_VLAN_Filtering.sh

      - name: Run Test_globally_enabled_DAI
        working-directory: ./tests/UsingDynamicParameters/
        run: ./Test_globally_enabled_DAI.sh

      - name: Run Test_static_ACL_Enabled
        working-directory: ./tests/UsingDynamicParameters/
        run: ./Test_static_ACL_Enabled.sh
      
      # Run Core_DAI_Features Tests

      - name: Run Test_ARP_Poisoning
        working-directory: ./tests/CoreDAIFeatures/
        run: ./Test_ARP_Poisoning.sh

      - name: Run Test_Communication_after_DHCP_Snooping
        working-directory: ./tests/CoreDAIFeatures/
        run: ./Test_Communication_after_DHCP_Snooping.sh

      - name: Run Test_Communication_from_Unacknowledged_Sources
        working-directory: ./tests/CoreDAIFeatures/
        run: ./Test_Communication_from_Unacknowledged_Sources.sh

      - name: Run Test_Static_Entry_In_The_ARP_Table
        working-directory: ./tests/CoreDAIFeatures/
        run: ./Test_Static_Entry_In_The_ARP_Table.sh

      - name: Run Test_Trusted_Interfaces
        working-directory: ./tests/CoreDAIFeatures/
        run: ./Test_Trusted_Interfaces.sh

      - name: Run Test_Untrusted_Interfaces
        working-directory: ./tests/CoreDAIFeatures/
        run: ./Test_Untrusted_Interfaces.sh

      - name: Run Test_Above_Rate_Limit
        working-directory: ./tests/CoreDAIFeatures/
        run: ./Test_Above_Rate_Limit.sh

      - name: Run Test_Below_Rate_Limit
        working-directory: ./tests/CoreDAIFeatures/
        run: ./Test_Below_Rate_Limit.sh