name: Module Is Buildable Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4
      
      # Install required dependencies
      - name: Install Build Essentials
        run: sudo apt-get update && sudo apt-get install -y build-essential
      
      # Compile the code
      - name: Compile Code
        run: make
